### ISSUE TITLE
Feature request: ability to define hashKey globally

### ISSUE THREAD

**Issue by crhistianramirez** [oliverheywood451/ordercloud-javascript-catalyst#1]
`withOCWebhookAuth` takes as the second parameter the hashKey. In many cases an application will use the same hash key for all of its webhooks. It would be ideal not to have to define that every time and instead allow it to be defined globally.

Given that both nextjs and express run on node, i think its safe to use `process.env.{VARIABLE_NAME_HERE}`

**Comment by oliverheywood451** [comment]
Should be done. That second parameter is now optional. The default is process.env.OC_WEBHOOK_HASH_KEY

There are examples of each in the main readme
